### ISSUE TITLE
Tagging Absent Officers

### ISSUE THREAD

**Issue by zme1** [zme1/toscana#10]
As I've been making my way through the meeting minutes, I got the impression that it would probably be of interest to note who is absent and how often they miss meetings. The only attendance taken is of officers, so it's about 2-4 every meeting. It seems like some people miss more meetings than others, and it affects their position in the Lega if they seem to miss too much.. If I wanted to easily integrate this into my tagging system, is there an attribute that could take a value that would express this? I was looking at @ana and haven't had much other luck as far as conceiving a systematic tagging system..

**Comment by zme1** [comment]
@ebeshero Any thoughts?

**Comment by ebeshero** [comment]
@zme1 Thinking about this, much may depend on the way the absences are indicated in the minutes. Do the officers change over time, or is this a static group? (I imagine it is probably changing over the years you are covering?) Can you tell the terms of the officers, so you always know who is expected? 

If roll is taken and absences noted, you could indicate that in two separate TEI `<list>` elements with `@type` attributes. But if the absences are not recorded and you are noting them yourself, I might recommend a TEI `<note>` element, perhaps with `resp="zme1" type="impliedAbsence”` or something like that, and indicate the persons you think are missing inside. For meta-info like that, you can either try inline solutions in the text of the minutes or, or find a good place in the `teiHeader` for each set of minutes to record those present and absent. I am not sure exactly where you might put that in the `teiHeader` without further study, though—it’ll take a little research in the Guidelines!

**Comment by ebeshero** [comment]
@zme1 My first thought, though, was just to handle absences, if unrecorded, with no extra markup. If each person has a distinct id, you can do some XPath to find the list of dates on which they are present and accounted for, as well as the dates on which they are missing. Does that work just as well?

**Comment by zme1** [comment]
@ebeshero I'm sorry, for some reason my Github email notifications are being flagged as spam and I'm not getting them... *sigh*

Anyways, I had originally used a `<list>` element with a @type value of "absent" to account for the officers who were not present (as they *are* explicitly noted at the very beginning of every meeting), but I ultimately decided against doing that and erased it for two reasons:

1. Fear of tag abuse
2. There are lists of people riddled throughout the entire volume, but only *some* are in true list format. I thought that if I wrapped the "lists" that appear in prose rather than in true list form, that may be an issue later on when I want to render the transcriptions in HTML.

**Comment by ebeshero** [comment]
@zme1  Let's find out how to **unflag** those in your e-mail...I think you just need to visit the spam folder, identify messages from Github, move them to your inbox, and usually thereby remove them from the spam filter. That's important! 

As for the absentee rosters: Okay--I wasn't clear on the document details!  But it's not tag abuse to use `@type` on a list, and lists aren't necessarily *only* about formatting in TEI. You could think of it as a *conceptual* list: If it's a list of names not worked into a sentence and divided regularly and reliably by *some kind of separator* (perhaps commas, perhaps something else) you could reproduce the list items as a string of text with commas in between using XSLT or even XQuery. It'll work. But if the absentee rosters are *unevenly* formatted, the TEI `<list>` might not be the best choice. Much depends, too, on how important the duplication of punctuation and formatting is to the project: You *could* decide to make a comment in your editorial apparatus that you're *regularizing* certain uneven phenomena for the purposes of searching and working with the data in the minutes. (You could make a general statement somewhere up in the TEI Header, like in the encodingDesc--we can look up the best place.)

If you *don't* use a `<list>`, what makes sense? Having a single element wrap around a group of names that are marked "absent" seems helpful, and having the individual names be reach-able by XPath as children of a common parent with an attribute of "absent" seems the right thing for processing and rendering. Perhaps you want an easy way regularly to distinguish those absent from those present in a reading view of the minutes in HTML? 

There's also an `@rend` you can use on `<list>`, and with it you might come up with some simple values like `inline` or `comma-sep` to help your processing later. I don't know if that helps? If regularizing these in the document structure as lists doesn't seem the right thing to do, let's see if we can come up with something that communicates the list hierarchy as simply and regularly...

**Comment by zme1** [comment]
@ebeshero My email server won't let me release any of the emails to my inbox, so I'll have to go to IT and see if they can help me tomorrow/Monday...

Do you think that if I re-applied a `<list>` element to those names and simply added a @rend attribute with a value of "list" to all of those that will *actually* be rendered as a list in the minutes could be a potential solution? If that makes sense.

**Comment by ebeshero** [comment]
@zme1 That should work! As for your e-mail, is it Pitt's filters that are filtering GitHub? You can manipulate those in http://my.pitt.edu : Look for "Spam and Virus Filtering"--for me it's on the lower right-most column on that page.

**Comment by zme1** [comment]
@ebeshero Ok, great. I'll have *both* of those issues taken care of today. Many thanks!!!!!
