### ISSUE TITLE
XSLT variable use for visualizations

### ISSUE THREAD

**Issue by zme1** [zme1/toscana#14]
I am currently starting to kick off my SVG visualizations, and my first one is going to be a line graph that plots acceptances and dismissals from the Lega in intervals of 6 months. Each calendar year has its own separate .xml file, and I want to be able to access each one individually in my stylesheet to build the graph. 

I wonder if there is a more proper and/or efficient way to create variables for entire files in my stylesheet. What I have written is below:

```
    <xsl:variable name="minuteColl" select="collection('../../TEI/meetingMinutes')/*"/>
    <xsl:variable name="yr1919" select="collection('../../tei/meetingMinutes/1919.xml')"/>
```

This seems inherently wrong to me for two reasons... 1. It's repetitive, and 2. I'm referring to a single file with a `collection()` function. @ebeshero @djbpitt Can I go about this another, more frugal way?

**Comment by zme1** [comment]
(disregard the original issue comment; I didn't use those year-by-year variables) 

   I just pushed my first line-graph output into my repository (without lines drawn), and I'm very worried that it's not at all as clear as I thought it'd be. Firstly, I have no idea how to create lines based on the code that I've written, which is overly confusing code-vomit, I think, and secondly, the information itself seems to be ill-conveyed on the line graph. It's supposed to show (on an annual basis) the number of members who enter the league (blue dots) vs. the number of people who leave (red dots). I plotted points in 6-month intervals, and contrasted different years with shading behind each area. The graph seems like it doesn't clearly convey the information I want.. Any input at all is greatly appreciated! Sorry for the late messages....

   PS. The output is in visualizations/svg_graphs and my xslt file is in xslt/html

**Comment by ebeshero** [comment]
@zme1 You may have found this out already, but to isolate a document rather than a collection, use the XPath `doc()` function. To my delight, there’s a terrific little slideshow on this function with some common applications of it by a friend of ours who used to serve recently on TEI Council: http://web.uvic.ca/~mholmes/dhoxss2013/handouts/doc_function.pdf

I am about to start my day of schlepping from airport to airport, so I will try to take a look at your data viz efforts when I am parked at my gates..

**Comment by zme1** [comment]
@ebeshero I made a new bar-chart with the same data, since I thought that (while I want to stay away from bar charts as much as I can this term) it seemed like it was much more clear with the data. Instead of plotting six-month intervals, I just lumped all acceptances and dismissals into one number for each year. It's still quite convoluted, though. Gotta shake off the SVG dust!!

**Comment by zme1** [comment]
(and both are now in my repo)
