### ISSUE TITLE
Embedded SVG

### ISSUE THREAD

**Issue by djbpitt** [zme1/toscana#20]
The invisible bars in the bar graph happened because HTML5 with HTML syntax (served as mimetype text/HTML) doesn’t understand namespace prefixes. See https://stackoverflow.com/questions/22806022/how-to-use-svg-namespace-in-xhtml-documents. The fix is either to declare the namespace in place without using a prefix (which is what I did) or change the filename extension to .xhtml, which will change the mimetype.

**Comment by ebeshero** [comment]
@djbpitt Is this something I can address on my newtFire server by controlling the mimetype for .html files? I've been developing xhtml an with the .html extension and usually without an xml line at the top, trying to have my proverbial cake and eating it too. That said, I think there's no reason you can't serve .xhtml extensions on my server; it's just inconsistent with the usual practice over here.

**Comment by djbpitt** [comment]
@ebeshero You can change the mimetype for `.html` files, but if you’d like to be able to serve as both `text/html` and `application/xhtml+xml`, you can set `.html` for the former and `.xhtml` for the latter, which is what I’ve done on Obdurodon. The configuration file to map mimetypes to filename extensions on my system is `/etc/mime.types`, but I’m running a different Linux distro than you, so yours may be located elsewhere. You can read more about the effect of the mimetype at <https://www.w3.org/International/articles/serving-xhtml/>.
