### ISSUE TITLE
Order of persons in heatmap

### ISSUE THREAD

**Issue by djbpitt** [zme1/toscana#28]
@zme1 The persons in the heatmap (in the `heatmap` branch) are currently ordered alphabetically. That’s convenient for looking up a particular person (or, at least, it will be once the axes have been labeled), but it isn’t a natural or intrinsic order the way the order of dates is. Would it be more insightful to order the persons from most engaged (greatest total number of committees over the duration of the logs) to least?

**Comment by zme1** [comment]
@djbpitt That may be a decision we make once the map is closer to its full size. As of now, ranking the members by activity would help improve the map's legibility, but the issue of parsing the data by member may become easier once the map's size is increased. I do suspect, though, that in either case ranking by activity would highlight individual member activity.
