### ISSUE TITLE
Null attribute values

### ISSUE THREAD

**Issue by djbpitt** [zme1/toscana#29]
@zme1 In the` officerGenMember_data.xml` file there are 15 null attribute values, 3 for `@ref` attributes and 12 for `@when` ones. The first example is: https://github.com/zme1/toscana/blob/d361e8b4bd8f9c3b92cb298c2edab0a32df45a9e/xml/officerGenMember_data.xml#L1080

**Comment by zme1** [comment]
Fixed!

**Comment by zme1** [comment]
Unfixed! I have to step away from my computer for about 2 hours, but I'll try to patch this when I'm back online.
