### ISSUE TITLE
Server pages won't update?

### ISSUE THREAD

**Issue by zme1** [zme1/toscana#30]
I've been modifying my webpages throughout the day, and I keep having trouble updating my files on the server to reflect the local changes. Right now, my lega.css file won't update with my current local version. My website won't reflect *any* updates to my CSS file, even when I completely remove it from the server. Is there something I am or am not doing that's causing this? @ebeshero

**Comment by ebeshero** [comment]
@zme1 Let me take a look at what's posted on the server. In the meantime, check the following:
1) What's the relationship by filepath between your CSS file and the page(s) it's styling? Is that CSS sitting in the same relative association on the server? 

2) Try opening your page in a different web browser and hitting refresh...sometimes CSS files are cached in your browser (so you could try clearing your browser cache). 

Taking a look to see what I can see on the server...

**Comment by zme1** [comment]
@ebeshero It looks like I needed to clear my browser cache from my laptop to see the refreshed styling properties. I never would have thought to do that.

**Comment by ebeshero** [comment]
@zme1 Here's a snip of your keyMembers.html page as I'm seeing it on my computer: I can see that you've got a transparent background on this graph, which I thought was pretty cool, so I took a screen capture of it. Does this look like your current CSS styling?

<img width="1381" alt="screenshot 2018-04-01 20 58 34" src="https://user-images.githubusercontent.com/4014518/38179288-7936b2f2-35ef-11e8-9055-6c62ac1a1826.png">
