### ISSUE TITLE
Formatting Heat Tables

### ISSUE THREAD

**Issue by zme1** [zme1/toscana#34]
I'm trying to finish my heat table formatting, so that the information is displayed legibly as the user selects a map cell, and I'm *almost* there. I just have one more bug to work out, and I can't figure out how to proceed from the manner in which I've processed it. As a refresher, my XSLT file is in `xslt/svg/heatmap_tables.xsl`, my input is `xml/officerGen_pipelineData.xml`, and my output is in `html/ssi/visualizations/heatmap_tables.html`. I've written an `xsl:variable` (of which I'm embarrassingly proud at the moment) that processes all the information as I'd like it to, except I can't determine how to tell the stylesheet **not** to add an additional semicolon delimiter after the last item in the sequence of activities. My variable is below:

```
                    <xsl:variable name="activity">
                        <xsl:for-each select="$root//act[@ref eq $currentPerson and $currentDate eq date/@when]">
                            <xsl:variable name="type" select="@type"/>
                            <xsl:variable name="subtype" select="@subtype"/>
                            <xsl:variable name="role" select="@role"/>
                            <xsl:variable name="concat">
                                <xsl:if test="$type eq 'proposal' or $type eq 'officer'">
                                    <xsl:value-of select="$type"/>
                                </xsl:if>
                                <xsl:if test="$type eq 'committee'">
                                    <xsl:value-of select="concat($subtype, ' ', $type, ', ', $role)"/>
                                </xsl:if>
                            </xsl:variable>
                                <xsl:value-of select="concat($concat, '; ')"/>
                        </xsl:for-each>
                    </xsl:variable>
```

An example of the output is below:

```
   <tbody class="heatToggle" id="tbody-zinim192311" style="display: none;">
      <tr>
         <td>#zinim</td>
         <td>1923-11</td>
         <td class="activity">officer; ballo committee, assistente; </td>
      </tr>
   </tbody>
```

@djbpitt @ebeshero Is there any simple fix to my current method, or is it best to take another approach to accomplish this?

**Comment by zme1** [comment]
As it stands right now, in my document template, I'm simply calling on this `$activity` variable directly inside the appropriate table cell.

**Comment by djbpitt** [comment]
@zme1 The easiest way not to add a delimiter after the last item is to use `string-join()`. If you can’t do what you need with that, are you available to consult on Thursday, April 19? I’m free for a bit beginning at 12:00.

**Comment by zme1** [comment]
@djbpitt The problems I'm having with that are:

   1. If I perform a `string-join()` anywhere inside my `$concat` variable, there won't be any joined strings, since it's only processing one activity at a time.
   2. If I try to move the `string-join()` outside the for-loop just inside the `$activity` variable, then the `$concat` variable is no longer in scope, since it's nested inside the for-loop. 
   3. If I place the `string-join()` inside the actual table cell, all the activities are processed as one single running string of text, again with nothing to join.

I think I'll try to swing by tomorrow afternoon to try and sort this. Would around noon work for you?

**Comment by djbpitt** [comment]
@zme The way I usually use `string-join()` with `concat()` is that I string-join the stuff that needs to be string-joined, save it in a variable (it’s usually just a convenience variable, but convenience is worth something, too), and then conjoin the variable with other stuff using `concat()`. This conversation will be easier over a keyboard, though, so let’s pick it up again Thursday, April 19 at noon in my office.
