### ISSUE TITLE
Committee Network Input 

### ISSUE THREAD

**Issue by zme1** [zme1/toscana#37]
@ebeshero @djbpitt I haven't written any code for my network input, but I have a question regarding the .tsv file I'll be making for the input...

Intuitively, I want to loop over every committee list in the volume and tell it "for every member on this committee, generate one line tab-separated line for the current member and every other member on the committee." But it seems to me that this kind of output would double my desired results, for every connection has two members, which will then output two lines for each, instead of just one. Am I approaching this the wrong way?

**Comment by zme1** [comment]
@djbpitt To bring you up to speed, if you see this... I am making another social network that visualizes committee activity. The committee members will be nodes, and the committees on which they serve will be the edges.

**Comment by zme1** [comment]
I think if I write the template so that each member generates a tab-separated line for every member and only their following members in the list, I think that should work, right? At least that's what my duck told me....

**Comment by ebeshero** [comment]
@zme1 Yes, that's exactly how you want to do this: it's basically setting loops inside loops. What's tricky about that is "holding your place" in the outer loop when you open a sub-loop: you need to set a local variable to store that value . You start with the committee, *set a variable* to hold each distinct member and store the `current()` committee you're standing on. Then open a loop inside the loop for each committee member, to find all the other committee members who are `not(. = current())`. Output *those* one by one with your concatenated tab-separated list, and end it with a line-feed character.

**Comment by ebeshero** [comment]
@zme1 Re-reading your post, I guess what I described isn't really what you and your duckie were discussing... There are multiple ways to do this, but you might think of it as:
1) stop on each committee, save its `current()` value (for your `$edge`) in a variable, 
2) get its list of individuals and store it in a variable (for your `$sourceNode`),
3) for each member of that list, define a local variable to find everyone else in the committee who isn't your `current()` person, and you have your `$targetNode`. 
4) return your `concat()` list of `$sourceNode`, `$edge`, and `$targetNode` with tabs and line-feed.

**Comment by zme1** [comment]
@ebeshero I was able to successfully go into every list and output a full `.tsv` file with every node connection. Since it will be a co-occurrence network (and therefore undirected), I only have one connection for each member combination, rather than every person appearing in the source and target node. Is that the correct approach? I figured just one edge connection in this context is the correct way to process these relationships..

**Comment by djbpitt** [comment]
@zme1 In an undirected graph, you can omit the reciprocal edges. This is described as representing the data as a **triangular matrix** (usually qualified as **upper triangular matrix** or **lower triangular matrix**, depending on which half you throw away after slicing the full [rectangular] matrix on the diagonal but since they’re symmetrical, it doesn’t matter which).
