### ISSUE TITLE
Error on p. 95

### ISSUE THREAD

**Issue by djbpitt** [zme1/toscana#38]
@zme1 A note in English appears in the Italian column for p. 95 (1922), and when I checked the XML, it looks as if there’s a note by a transcriber in Italian in that entry, as well. You may want to format or suppress `<note>` elements when generating the reading view.

**Comment by zme1** [comment]
@djbpitt For the time being, I wrote a template that surpasses the transcriber's notes throughout the volume, of which I think there are 5 or 6 in total (and their principal purpose was to either describe a marked feature of the manuscript scan, or to annotate a tagging decision I made in regards to my computational research). Being that the scans are immediately available to view and my own comments are more for documenting my own processing, I will circle back to this problem at a later point and reinsert those transcriber notes back into the volume.
