### ISSUE TITLE
ODD Marks <teiCorpus> Invalid

### ISSUE THREAD

**Issue by zme1** [zme1/toscana#4]
I just did a first attempt at my ODD, and I'm unsure how to confront my very first problem... I must have botched the ODD syntax somewhere, because my schema flags ```<teiCorpus>``` as invalid. It's cited in my ```<moduleRef>``` element, and I did not modify its contents at all. I'm not sure at all what I may have done.

I pushed my ODD file to the repo for reference.

**Comment by zme1** [comment]
I realized my error! Now to tend to the hundreds of freshly appeared red ticks.......

**Comment by ebeshero** [comment]
@zme1 Ah! I had just pulled in your files to inspect what was wrong (because my first two guesses didn't pan out). What was the error with teiCorpus?

**Comment by zme1** [comment]
Well, in the element schemaSpec, the second attribute, @start's value was "TEI" instead of teiCorpus. That was a real head scratcher for about 25 long minutes!

**Comment by ebeshero** [comment]
@zme1 Ahhh--that would do it: you've changed the start element for the file. 
By the way, nice work on the TEI header for the corpus. May I lobby for an additional credit to the DH Advanced Praxis Group, sponsored by Pitt-Greensburg's Center for the Digital Text (for long range fame and glory and all that?) :-)

**Comment by ebeshero** [comment]
(Clearly, I'm working on institutionalizing this operation.) If I'm getting a cite it would be as part of a consulting group.

**Comment by zme1** [comment]
Of course! I will happily attribute you and the class!

**Comment by ebeshero** [comment]
Thank you! :-) Debugging ODDs is an Advanced TEI rite of passage...I'm going online for a Hangout meeting with some TEI people at 3pm, but I'll see if I can answer questions as they come up this weekend. Good luck!

**Comment by zme1** [comment]
I'm now at the point where I suspected I would have the most trouble... I want to alter the content model for ```<ab>``` so as to permit the use of ```<closer>``` as a child element? I have my first attempt recorded on my ODD, but since there are no examples of this type of document customization that I can find anywhere, my resourcefulness is limited here.

**Comment by ebeshero** [comment]
@zme1 There are a few different ways to handle this: one might involve redefining the element's content model, but another may be to assign either `<closer>` or `<ab>` to a different module...it'll take a little reading to sort out the easiest way... My instinct (before digging in and looking up the element specs and module definitions) is to try to add `closer` to a module that would that permit it to be used in `<ab>`...

**Comment by ebeshero** [comment]
@zme1 Also, I think I've got some examples of this sort of thing for you to look at...I did something like this recently with the ODD I re-defined for the Shelley-Godwin TEI files we're tweaking in the Pgh-Frankenstein project...I'll post a link in a sec...

**Comment by ebeshero** [comment]
@zme1 Here's the ODD file I was thinking of: https://github.com/ebeshero/Pittsburgh_Frankenstein/blob/master/collateXPrep/sga_Notebooks/sga_schemata/shelley-godwin-Pgh.odd 

Look at the `<elementSpec>` elements here...And remember the ODD  resources we went over last October--the slide set from Syd Bauman? He has some examples there to look at, too: Those resources are here: https://github.com/ebeshero/DHClass-Hub/wiki/TEI-ODD:-Schema-Prep-Resources-for-TEI-in-Projects

**Comment by ebeshero** [comment]
@zme1 Did you come up with a good way to redefine ab or closure?

**Comment by zme1** [comment]
I haven’t yet. I was only able to work on that for about 45 minutes after I saw your responses, but I’ll be working on it again early tomorrow!

Le 20 janv. 2018 à 19:32, Elisa Beshero-Bondar <notifications@github.com<mailto:notifications@github.com>> a écrit :


@zme1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzme1&data=01%7C01%7Czacharyenick%40pitt.edu%7C615f227a7d0344dca55e08d560666781%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=gH2%2Fca%2FO6lyL3g%2F979VC7xAeLXftnDOAhxVexHiUAI0%3D&reserved=0> Did you come up with a good way to redefine ab or closure?

**Comment by zme1** [comment]
@ebeshero I do believe I was able to (finally) figure it out with the help of your ODD file as reference. Would you mind looking at my code at your earliest convenience to see if it's what you anticipated I should have done (and also to check out the credit for you and the class in the teiHeader to see if it's to your liking)?

**Comment by ebeshero** [comment]
@zme1 I'm taking a look now...

**Comment by ebeshero** [comment]
@zme1 I like this ODD! I see how you've customized the `<persName>` and `<rs>` elements to work with the `@role`attribute, which should be one of the major classification strategies for your network analysis. One terrific side-effect of defining attribute lists is that they become available in oXygen for those marking the XML and using your attributes: As soon as someone applies `@role` they'll see a handy drop-down list of values pop up in oXygen.  And your re-definition of `<ab>` makes perfect sense here: You've customized this element as a structural / contextual container for the elements you're setting inside.

Is it working as you expect? Try setting these elements inside `<ab>` to make sure, once you've associated the schema. Troubleshooting (if you need it): Double-check your `@module` values in the ODD: It's easy for the wrong module to passively be defined as the "home" of a TEI element (especially if, like me, you've pasted in the code and modified it). You won't see an error in the TEI ODD file if you've set the wrong module, but you'll see the results as you're coding the schema-associated TEI minutes file.

**Comment by ebeshero** [comment]
@zme1 One thing you can do is design your ODD to share with others in the TEI community who might be trying to capture similar kinds of data in similar kinds of documents. I've heard plans for the [TEI website](http://www.tei-c.org/index.xml) to include a page of ODDs volunteered by project designers like yourself, and I'm hoping that'll go online soon! What you'd want to do is just add some XML comments to the ODD explaining your decisions in customizing and altering the content model of particular elements as you did. That's a good strategy for explaining the encoding to your project team and anyone visiting your project: the ODD can be a sort of gateway for those looking "under the hood" at your data collection and editing work.

**Comment by zme1** [comment]
ODD annotations will be a little project for early this week!

**Comment by zme1** [comment]
As for the schema, everything seems to be in good working order, but I am yet to create any of my schematron rules, which I'm hoping will tighten my files up more. I have a fear that my schema may not constrain as strictly as I want it to, so the ODD will be a continual work in progress while I still refine all my tagging.

**Comment by ebeshero** [comment]
Yes, that's quite likely in this early stage--it takes a schema a while to mature. But I think you're off to a strong start, and I think the Praxis group will benefit from taking a look at your work, too!
