### ISSUE TITLE
Quotation marks and apostrophes

### ISSUE THREAD

**Issue by djbpitt** [zme1/toscana#43]
@zme1 Quotation marks and apostrophes would look better if they were curly, rather than straight.

**Comment by ebeshero** [comment]
@zme1 And there are ways you can control quotation marks with CSS, if you've used the `<q>` element in HTML to control quotation marks.

**Comment by ebeshero** [comment]
See https://github.com/ebeshero/newtFire-webDev/blob/d2eb76f027b5009501f1bee66c548d3789767966/nfIndex.css#L52

**Comment by djbpitt** [comment]
I usually manage paired quotation marks with `<q>` and CSS, as @ebeshero suggests, although I’ve been criticized (fairly) for not distinguishing quotation marks that demarcate quotations from those used for other purposes. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/q, which refers to “text *is* a short inline quotation” (emphasis added). But even if `<q>` with CSS handles single and double quotation marks when they’re paired around text, isolated apostrophes need to be entered as curly apostrophes. The keyboard shortcuts are documented at https://www.typewolf.com/cheatsheet#quotes-and-apostrophes.

**Comment by zme1** [comment]
@ebeshero @djbpitt Thank you, both, for all the feedback you're giving on the site. Although most of the heavy lifting is now (temporarily) finished, I'll spend the week going through the site, validating pages, and revising any broken, unsightly, or incorrect moments on the pages. I still have some transformation work to do on the reading view, but I'll be combing through the site after!

My family is going on an impromptu 2-day trip this afternoon, so I won't be pushing anything after this morning until Wednesday or Thursday -- just so you both know.

**Comment by ebeshero** [comment]
@zme1 Happy travels! We'll just leave some issues here for safe-keeping until your return.
