### ISSUE TITLE
About the Heinz History Center (and aboutSources corrections)

### ISSUE THREAD

**Issue by djbpitt** [zme1/toscana#45]
You may want to update the information about the Heinz History Center on http://toscana.newtfire.org/html/aboutSources.html. :-) On that same page, several of the items in the bulleted list at the bottom have doubled double quotation marks (and straight ones, where curly would be better; see #43).

**Comment by ebeshero** [comment]
On the same page, you've listed me as directing the Center for Digital Texts, but it's really the Center for the Digital Text. (The link is fine, and thank you for the shout-out!)
