### ISSUE TITLE
TEI Header suggestions

### ISSUE THREAD

**Issue by ebeshero** [zme1/toscana#5]
@zme1 I'm taking a look at your TEI header as requested.  I think you can just call me and the Praxis group "consultants" on your project! Here's a rewrite for this line: 
https://github.com/zme1/toscana/blob/50a18ed6939c9f3d135c5809807f28374ce52461/TEI/meetingMinutes/meetingMinutes_vol1.xml#L23
```
 <respStmt>
               <resp>Consultants on project development: </resp>
               <persName ref="#bondarE">Elisa Beshero-Bondar</persName>
              <orgName>Spring 2018 DH Advanced Praxis Group</orgName>
               <orgName>Center for the Digital Text at the University of Pittsburgh, Greensburg</orgName>
            </respStmt>

```
I just tested the code in oXygen to make sure it's valid TEI and it appears so, so I'm just sending that back as a pull request.

* I was thinking about your use of `<idno>` to refer to the Heinz History Center's website, and I realized in checking the code that you can't use `<ptr>` or `<ref>` there (which is what I was expecting--the typical elements to hold link addresses. That decision looks good to me, now that I realize why you needed to use it. `<idno>` is typically used for catalog numbers and other identifiers and I think a URI is a good use for it. 

* I particularly like what you've done with the `<profileDesc>` to describe the source texts! Here I'm wondering about *this* use of `<idno>`:
```
<idno>2015.0079 and 2017.0123</idno>
```
Are these two separate catalog numbers? I think that's probably okay, and I realize that TEI doesn't permit two sibling `<idno>` elements side by side, but [TEI does allow you to set children `<idno>` inside a parent](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-idno.html), like so:

```
<idno>
     <idno>2015.0079</idno> and <idno>2017.0123</idno>
</idno>
```
If those are catalog numbers you may want to isolate them later in distinct ways, and this format might all you to add some commentary about them, as in:

```
<idno>
      Minutes  of 1923-1924: <idno>2015.0079</idno> and Minutes after 1924:
 <idno>2017.0123</idno>
</idno>
```
(something like that?)

**Comment by zme1** [comment]
I was hoping there was a workaround for the ```<idno>``` elements, but it never occurred to me to nest them inside each other in that way. I'll make these changes; they are all great suggestions! Thank you, as always.

**Comment by ebeshero** [comment]
@zme1 I just saved you the trouble! Because I wanted to see if my suggestions were valid TEI, I just made edits here: Here's the pull request: 
 https://github.com/zme1/toscana/pull/6/commits/b55c4ca023c31a4b542c6a65960f6af6e66dbd6b

**Comment by zme1** [comment]
Thank you!!!!
