### ISSUE TITLE
Project Update

### ISSUE THREAD

**Issue by zme1** [zme1/toscana#52]
@ebeshero I have been quietly working on my project and finished tagging my corpus about a week ago (with additional modifications made to my ODD file -- and abundant Schematron rules to match). Since, I've been brainstorming some different analyses I want to run on the corpus and began my first visualization this weekend. My analyses don't appear that they will be overly complex as far as information; my only issues primarily revolved around accounting for interesting complications for specific presentation (e.g. I needed to perform another headache of a double `for-each` loop over my newest visualization to illustrate the varied authorship across the minutes). I could write a long post here on all my updates, but I'd rather try to see if we could schedule a Hangout session just to catch up. If you aren't too busy in the next week, I'd love to meet up online and review what's been done and what's still left to accomplish!

**Comment by ebeshero** [comment]
Hi @zme1 ! Well, I'm actually in New Haven, CT this week, about to start some intensive photography of Mitford papers in the Beinecke Library at Yale. I think we can arrange a Hangout during the week, but it might be best if you caught me this evening before the archival distraction begins for me. The Beinecke is open from 9am to 7pm through the week, and I'll likely try to max out my time there. Are you free this evening?

**Comment by zme1** [comment]
@ebeshero I actually am! I have other schoolwork to do tonight, but it shouldn't occupy my entire evening and I'm flexible with when I actually work on it. I caught you just in time!

**Comment by ebeshero** [comment]
@zme1 Good--want to meet now? See you in Hangouts...
